### ISSUE TITLE
Callback not working in latest NPM release

### ISSUE THREAD

**Issue by Harti** [innovato/fontanimate#2]
I'm having trouble making the callback work. Even the bluntest of "debug" functions, `console.log` and `alert` won't get triggered at all.

During my search I've found a similar issue on StackOverflow: https://stackoverflow.com/questions/50665940/unable-to-animate-font-awesome-icon-using-vivus

My personal use case is too bloated to put it up on JSFiddle, but they did it.

Maybe you can look into the issue and help us troubleshoot the issue. I've looked at the source code and there is absolutely no reason why the callback would not get called, unless Vivus doesn't ever actually finish. 
If it truly never finishes, there has to be some issue with the code either on their end or on yours. I really do not know, but I do wish that callbacks worked.

**Comment by Harti** [comment]
Oh. Huh. I found the issue.

The commit with the callback change *was not released*. NPM installs 0.1.0 which doesn't include the callback function.

As a temporary workaround, you can use `npm install innovato/fontanimate#master --save`.

What gives?

**Comment by wkonecny** [comment]
@Harti thanks for creating this issue! I was sure that I published all of it, but i guess not. I will check this out today and publish version 0.2.0 asap.

**Comment by wkonecny** [comment]
I have published 0.2.0.
