### ISSUE TITLE
[Question] Usable with pseudo-elements?

### ISSUE THREAD

**Issue by guillaumegarcia13** [innovato/fontanimate#3]
What if Font Awesome icons are actually rendered using pseudo-elements such as :before and :after?
Is this still usable and how?

**Comment by innovato** [comment]
Thanks for your question! This plugin works _only_ when Font Awesome icons are rendered using SVG. The SVG icons are animated using stroke offset. SVG graphics support stroke offsets out-of-the-box in.

The pseudo-elements use actual (*.ttf) font files. So they are textual characters. E.g. character `f0c8` is a rounded square in the `Font Awesome 5 Free` font-family. This plugin does not support the animation of text.

So unfortunately, the answer is no. :(
